### ISSUE TITLE
Link for custom OS not found

### ISSUE THREAD

**Issue by FeAlias** [MURobotics/Spot-Pi#1]
Hi, I am trying to download the custom OS at this link, https://github.com/MURobotics/Spot-Pi/blob/main/CHRIS

When I go there it says, "Page not found". Could you please help me find the right link? Thanks.

**Comment by Interaze** [comment]
I used to have one up, but I was restricted by the data limit for hosting it. Admittedly this is a very niche application as we were connecting to the University of Missouri's wifi, and it was a ubuntu image with a wpa supplicant and eth0 interface set. I'd personally recommend looking at that. Best practice would either fall on two extreme ends. Either I make a published/maintained image on some hosting platform to be pulled (which I unfortunately don't have time for atm), or just recommend pulling from ubuntu and entrusting that people working with spot can set up the necessary network connections on a linux OS. If you're at the University of Missouri we can always find a time to meet/chat about it some more.

**Comment by FeAlias** [comment]
Thanks for the reply. Maybe you could help me out with the project I’m
working on. I’m a tech teacher. I thought it would make a fun project to
show my class and inspire them this year by creating a robot dog similar to
what you all worked on. A lighter version. I’m teaching basic electronics
and I had the idea to have a robot dog walking around the room during class
to show them that they are learning is the foundation for larger projects
like robot dogs.

I bought a kit, the Freenove Robot Dog with plans to scale it up. I
understand the basic and I am able to work out the mechanical engineering
aspects. Unfortunately, the software for the kit is not very sophisticated.
I had hoped to upload a raspberry pi version of the Boston dynamics one but
I’m learning slowly that there is a lot I don’t know. My background is
materials science engineering so this is a new are for me.

**Comment by Interaze** [comment]
Ah. That helps to provide some context. The purpose of the Spot Robot is to abstract away the mechatronics layer of robotics (or to say, how can we provide users a reliable quadraped base that can fulfill the users requests). The idea is to reduce the 'reinventing the wheel' issue within robotics and allow companies and researchers to focus on higher order problems. As such, we don't get access to spot to program the motion of individual joints. Rather, we're able to provide a "walk" command. 

The raspberry pi OS is meant to serve as a brain to spot, not to balance, but to allow users to state where to go (It's like a motor cortex vs the frontal lobe of your brain), and, as such might not have what you're looking for/expecting. For building a robot dog, there are significant technical challenges at scale, a good video that covers a medium scale robot I'd look at the [open source dog v3](https://www.youtube.com/watch?v=yXA_KeuYpCY). The creater simplifies the inverse kinematics and feedback control for the end use, but power consumption and torque are a decent challenge with a design like this at scale. 

While my history of teaching is short, I have taught robotics within student organizations / helped lead a few projects and what I've personally found to help me was 'showing the magic'. Oftentimes, I do this by focusing on the problem we're solving with a robot as it's the vision behind it that we care about. Depending on what you're doing that can vary, but a few cool options are the irobot create 3s (great for programming), thingiverse has a few cool 3d printing robot arm kits you can try for the electronics as I saw you've worked with arduinos as well, which will require less intense specs per the scale. Feel free to let me know if that helps.

**Comment by Interaze** [comment]
Personally, my background is in SRE and Cloud Engineering, so my focus is on the orchestration and reliability of autonomous systems more than just the robot itself, which is where the spot can really help shine as I focus on a scale with them. Which is what my OnTheSpot project was hoping to tackle (as a very rough pre-alpha)

**Comment by FeAlias** [comment]
That does help a lot. Can I email you some follow up questions? What’s the
best way to email you?

**Comment by Interaze** [comment]
Certainly. cws3p4@umsystem.edu is the best way to contact me. I'm going to close this issue as well

**Comment by FeAlias** [comment]
Thanks for that. I sent one over to you.
